type PerfPhaseName = "script" | "domDiff" | "bindEvents" | "bindRefs" | "bootstrapNested" | "portals" | "restoreFocus" | "effects" | "total";
type PerfSample = {
    count: number;
    totalMs: number;
    maxMs: number;
};
type PerfComponentEntry = {
    renderCount: number;
    phases: Record<PerfPhaseName, PerfSample>;
};
export declare class Component {
    private el;
    private id;
    private rawTemplate;
    private renderFunction;
    private templateFn;
    private hooksSystem;
    private eventManager;
    private latestScope;
    private __ppRefStore;
    private __ppPrevRefStore;
    private __ppRefSeq;
    private isRendering;
    private props;
    private ownedChildren;
    private lastRenderedHtml;
    private renderCount;
    private trackedPortals;
    private parentId;
    private initialChildrenHtml;
    private pendingEventElements;
    private traversalCache;
    private _lastScopeKeySig;
    private _lastSortedKeys;
    private _cachedHooksAPI;
    private _propFnCache;
    private _interpolationFnCache;
    private _scopeEvalFnCache;
    private _refEvalFnCache;
    private static perfEnabled;
    private static perfStats;
    constructor(element: HTMLElement | SVGElement);
    static setPerfEnabled(enabled: boolean): void;
    static getPerfEnabled(): boolean;
    static resetPerfStats(): void;
    static getPerfStats(): Record<string, PerfComponentEntry>;
    private static createEmptyPerfEntry;
    private recordPerfPhase;
    private startPerfTimer;
    private endPerfTimer;
    private findOwnScript;
    private interpolateAttrString;
    private applyAttributeInterpolations;
    private computePropsFromAttributes;
    refreshPropsFromParent(): void;
    private extractOwnedTemplates;
    private maskNestedOwnedTemplates;
    private resolveOwnedChildren;
    private markOwnedEventHandlers;
    private getCachedFunction;
    private createRenderFunction;
    private unmountPreviousRefs;
    private createRefCaptureFunction;
    private makeHooksAPI;
    private restorePortaledElements;
    private applyPortals;
    private render;
    private applyDomDiff;
    private isInsideTrackedPortal;
    private morphChildren;
    private hasKeyedDirectChildren;
    private getNodeKey;
    private areNodesCompatible;
    private morphKeyedChildren;
    private collectDuplicateKeys;
    private morphNode;
    private collectEventElements;
    private hasEventAttributes;
    private walkOwnedBoundaryElements;
    private invalidateTraversalCache;
    private getTraversalCache;
    private collectManagedInputs;
    private syncAttributes;
    private bindRefs;
    private bootstrapNestedComponents;
    private saveFocusState;
    private restoreFocusState;
    forceUpdate(): void;
    destroy(): void;
}
export {};
