import { type ComponentHooksAPI, type ComponentRuntime, type PPContext } from "./ComponentRuntime.js";
import { type RpcOptions } from "./RpcClient.js";
import { type SocketHandle, type SocketOptions } from "./SocketClient.js";
export declare const ComponentInit: {
    bootstrap: () => void;
};
export declare class PPUtilities {
    protected static instance: PPUtilities | null;
    private readonly rpcClient;
    private readonly socketClient;
    private navigationEnabled;
    private boundHandleLinkClick;
    private boundHandlePopState;
    private boundHandleTrackedScroll;
    private isNavigating;
    private pendingHistoryStateSaveTimer;
    private lastHistoryStateSaveAt;
    private pendingProgrammaticScrollPersistenceTimer;
    private readonly RESET_SCROLL_ATTR;
    private readonly HISTORY_SCROLL_STATE_KEY;
    private readonly TRACKED_SCROLL_PERSISTENCE_INTERVAL_MS;
    private readonly PROGRAMMATIC_SCROLL_SETTLE_MS;
    private mounted;
    private suppressTrackedScrollPersistence;
    private transitionLockCount;
    private pendingRevealFrame;
    private pendingTransitionUnlockFrame;
    private hydrationBodySnapshot;
    private previousHistoryScrollRestoration;
    private trackedScrollElements;
    private didInitialScrollDiscovery;
    private readonly SCROLL_KEY_ATTR;
    static readonly PUBLIC_METHODS: readonly ["createContext", "mount", "redirect", "rpc", "socket", "enablePerf", "disablePerf", "getPerfStats", "resetPerfStats"];
    private constructor();
    mount(): void;
    createComponentRuntime<Props extends Record<string, any> = Record<string, any>>(hooks: ComponentHooksAPI<Props>): ComponentRuntime<Props>;
    createContext<T>(defaultValue: T): PPContext<T>;
    enablePerf(): void;
    disablePerf(): void;
    getPerfStats(): Record<string, {
        renderCount: number;
        phases: Record<"script" | "template" | "compile" | "domDiff" | "bindEvents" | "bindRefs" | "bootstrapNested" | "portals" | "restoreFocus" | "layoutEffects" | "effects" | "total", {
            count: number;
            totalMs: number;
            maxMs: number;
        }>;
    }>;
    resetPerfStats(): void;
    private disableTransitions;
    private enableTransitions;
    private requestFrame;
    private cancelFrame;
    private cancelScheduledHydrationReveal;
    private cancelPendingProgrammaticScrollPersistence;
    private beginProgrammaticScrollPersistencePause;
    private scheduleProgrammaticScrollPersistence;
    private scrollElementIntoView;
    private normalizeHydrationBodySnapshotStyle;
    private hideBodyForHydration;
    private scheduleHydrationReveal;
    private restoreBodyAccessibility;
    static resetInstance(): void;
    static getInstance(): PPUtilities;
    private enableSPANavigation;
    private disableSPANavigation;
    private handleLinkClick;
    private getNavigationTarget;
    private handleTrackedScroll;
    private handlePopState;
    private navigateTo;
    private resetGlobalCaches;
    private getResetScrollConfig;
    private getElementKeyFromElement;
    private handleScrollRestoration;
    private saveScrollPositions;
    private getElementKey;
    private registerInitiallyScrolledElements;
    private getTrackedScrollElements;
    private findScrollElementByKey;
    private cancelPendingHistoryStateSave;
    private buildHistoryState;
    private getScrollPositionsFromHistoryState;
    private persistCurrentHistoryScrollState;
    private getCurrentUrl;
    private teardownCurrentPageComponents;
    private updatePageContentWithViewTransition;
    private dispatchNavigationEvent;
    private showLoadingTransition;
    private fetchPageContent;
    private normalizeServerRedirectTarget;
    private getRedirectUrlFromResponse;
    private updateBrowserHistory;
    private updatePageContent;
    private syncBodyAttributes;
    private handleNavigationCompletion;
    private handleNavigationError;
    private findLoadingElement;
    private updateContentWithTransition;
    private parseTransition;
    private fadeOut;
    private fadeIn;
    private parseTime;
    redirect(url: string): Promise<void>;
    rpc<T = any>(functionName: string, data?: Record<string, any>, optionsOrAbort?: boolean | RpcOptions): Promise<T | void>;
    socket(functionName: string, args?: Record<string, any>, options?: SocketOptions): SocketHandle;
}
